import logging
import math
import re
from typing import List, Optional
import torch
from transformers import PreTrainedModel, PreTrainedTokenizer

logger = logging.getLogger(__name__)

RRM_PROMPT_TEMPLATE = """You are a helpful assistant in evaluating the quality of the responses for a given instruction.
Your goal is to select the best response for the given instruction.
Select Assistant 1 or Assistant 2, that is better for the given instruction. The two responses are generated by two different AI assistants respectively.
Do NOT say both / neither are good.
Here are some rules of the evaluation:
(1) If the instruction does not contain harmful content, you should prioritize evaluating whether the output honestly/precisely/closely executes the instruction, then consider its helpfulness, accuracy, level of detail, harmlessness, etc.
(2) If the instruction contains harmful content, prioritize the harmlessness and safety of the response.
(3) Responses should NOT contain more/less than what the instruction asks for, as such responses do NOT precisely execute the instruction.
(4) You should avoid any potential bias and your judgment should be as objective as possible.
Here are some potential sources of bias:
- The order in which the responses were presented should NOT affect your judgment, as Response A and Response B are equally likely to be the better.
- The length of the responses should NOT affect your judgement, as a longer response does not necessarily correspond to a better response. When making your decision, evaluate if the response length is appropriate for the given instruction.
(5) Your output should only consist of "\\boxed{{Assistant 1}}" if assistant 1 is better, or "\\boxed{{Assistant 2}}" if assistant 2 is better. Omit any other output.

## Query

{Query}

## Assistant responses

### Assistant 1

{Response_1}

### Assistant 2

{Response_2}

## Analysis Let’s analyze this step by step and decide which assistant is better, and then answer \\boxed{{Assistant 1}} or \\boxed{{Assistant 2}}.
"""


def stable_sigmoid(x: float) -> float:
    """Compute a numerically stable sigmoid function to prevent math overflow."""
    if x >= 0:
        z = math.exp(-x)
        return 1.0 / (1.0 + z)
    else:
        z = math.exp(x)
        return z / (1.0 + z)


class RRMJudge:
    """Uses a Reward Reasoning Model (e.g. RRM-7B) as a generative pairwise judge
    to evaluate response candidates.
    """

    def __init__(self, model: PreTrainedModel, tokenizer: PreTrainedTokenizer):
        self.model = model
        self.tokenizer = tokenizer
        self.device = next(iter(model.parameters())).device

    def parse_winner(self, output_text: str) -> Optional[int]:
        """Robustly parse the winner from the RRM generation output.

        The RRM model outputs ``\\boxed{Assistant 1}`` or ``\\boxed{Assistant 2}``.
        After ``tokenizer.decode()``, this arrives as a single backslash in the
        Python string (i.e. ``\\boxed{...}``).  The regex below handles both the
        single-backslash form (normal decode) and the double-backslash form
        (escaped in repr / logging) for robustness.
        """
        # Primary: match \boxed{Assistant N} (single or double leading backslash)
        match = re.search(r"\\{1,2}boxed\{\s*Assistant\s*(1|2)\s*\}", output_text)
        if match:
            return int(match.group(1))
        # Fallback: bare "Assistant 1" / "Assistant 2" mention
        match = re.search(r"\bAssistant\s+(1|2)\b", output_text)
        if match:
            return int(match.group(1))
        return None

    @torch.no_grad()
    def judge_pair_single(self, prompt: str, resp1: str, resp2: str) -> Optional[int]:
        """Perform a single directed pairwise comparison (Assistant 1 = resp1, Assistant 2 = resp2)."""
        formatted_prompt = RRM_PROMPT_TEMPLATE.format(
            Query=prompt,
            Response_1=resp1,
            Response_2=resp2
        )

        inputs = self.tokenizer(formatted_prompt, return_tensors="pt")
        input_ids = inputs["input_ids"].to(self.device)
        attention_mask = inputs["attention_mask"].to(self.device)

        outputs = self.model.generate(
            input_ids=input_ids,
            attention_mask=attention_mask,
            max_new_tokens=512,
            do_sample=False,  # Greedy decoding for consistent reasoning/judgment
            pad_token_id=self.tokenizer.pad_token_id,
        )

        generated_text = self.tokenizer.decode(
            outputs[0, input_ids.shape[1]:], skip_special_tokens=True
        )
        logger.debug("RRM Output: %s", generated_text)
        return self.parse_winner(generated_text)

    def judge_pair(self, prompt: str, resp_a: str, resp_b: str) -> float:
        """Evaluate a pair (resp_a, resp_b) symmetrically to control for position bias.

        Returns:
            float: 1.0 if resp_a is preferred, 0.0 if resp_b is preferred, 0.5 if draw or tie.
        """
        # Run forward comparison (Assistant 1 = A, Assistant 2 = B)
        win_fwd = self.judge_pair_single(prompt, resp_a, resp_b)
        # Run backward comparison (Assistant 1 = B, Assistant 2 = A)
        win_bwd = self.judge_pair_single(prompt, resp_b, resp_a)

        votes_a = 0
        votes_b = 0

        if win_fwd == 1:
            votes_a += 1
        elif win_fwd == 2:
            votes_b += 1

        if win_bwd == 1:
            votes_b += 1
        elif win_bwd == 2:
            votes_a += 1

        if votes_a > votes_b:
            return 1.0
        elif votes_b > votes_a:
            return 0.0
        else:
            return 0.5

    def run_tournament(self, prompt: str, candidates: List[str], temperature: float = 1.0) -> int:
        """Run Elo tournament over candidate responses to find the champion."""
        N = len(candidates)
        if N == 1:
            return 0

        ratings = [1500.0] * N
        paired_before = set()
        indices = list(range(N))
        k_factors = [40.0, 20.0, 10.0]

        for round_idx in range(3):
            k_factor = k_factors[round_idx]
            sorted_by_rating = sorted(
                indices,
                key=lambda i: -ratings[i]
            )

            pairs = []
            unpaired = list(sorted_by_rating)

            while len(unpaired) >= 2:
                a = unpaired[0]
                unpaired.pop(0)

                best_partner_pos = None
                for pos, b in enumerate(unpaired):
                    if (min(a, b), max(a, b)) not in paired_before:
                        best_partner_pos = pos
                        break
                if best_partner_pos is None:
                    best_partner_pos = 0
                b = unpaired.pop(best_partner_pos)
                pairs.append((a, b))
                paired_before.add((min(a, b), max(a, b)))

            for a, b in pairs:
                # Judge match outcome
                sa = self.judge_pair(prompt, candidates[a], candidates[b])
                sb = 1.0 - sa

                diff_ratings = (ratings[a] - ratings[b]) * math.log(10.0) / 400.0
                ea = stable_sigmoid(diff_ratings)
                eb = 1.0 - ea

                ratings[a] += k_factor * (sa - ea)
                ratings[b] += k_factor * (sb - eb)

        if temperature < 1e-5:
            champion = max(indices, key=lambda i: ratings[i])
        else:
            ratings_tensor = torch.tensor(ratings, dtype=torch.float)
            logits = (ratings_tensor * math.log(10.0)) / (400.0 * temperature)
            logits = logits - logits.max()
            probs = torch.softmax(logits, dim=0)
            champion = int(torch.multinomial(probs, num_samples=1).item())

        logger.info("RRM Elo Tournament finished. Champion: c%d (final ratings: %s)", champion, ratings)
        return champion
